app-name: demo-app
architecture: arm64
regions:
  us-west-1:
    cluster-name: us-cluster
    app-name: us-demo-app
    db_name: root
  eu-central-1:
    cluster-name: eu-cluster
    app-name: eu-demo-app
    db_name: root
