name: Hardcoded Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  fetch-credentials:
    runs-on: ubuntu-latest
    outputs:
      user: ${{ steps.set-creds.outputs.user }}
      password: ${{ steps.set-creds.outputs.password }}
    steps:
      - name: Set hardcoded user and password
        id: set-creds
        run: |
          # Hardcode the user and password values
          user="abc"
          password="abc@123"

          # Mask the user and password in the logs
          echo "::add-mask::$user"
          echo "::add-mask::$password"

          # Write outputs to $GITHUB_OUTPUT
          echo "user=$user" >> $GITHUB_OUTPUT
          echo "password=$password" >> $GITHUB_OUTPUT

  call-api:
    needs: fetch-credentials
    runs-on: ubuntu-latest
    steps:
      - name: Display user and password
        run: |
          # Access user and password from the previous job
          echo "User: ${{ needs.fetch-credentials.outputs.user }}"
          echo "Password: ${{ needs.fetch-credentials.outputs.password }}"
