name: Config Workflow

on:
  push:
    branches:
      - main

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    outputs:
      db_user: ${{ steps.read_yaml.outputs.db_user }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read YAML File
        id: read_yaml
        run: |
          # Use yq to extract specific data from YAML
          db_user=$(yq eval '.db_user' config.yaml)
          echo "::set-output name=db_user::$db_user"

  use-data:
    runs-on: ubuntu-latest
    needs: read-yaml
    steps:
      - name: Use DB User
        run: |
          echo "DB User: ${{ needs.read-yaml.outputs.db_user }}"
          # Use the DB user here
