# .github/workflows/main-workflow.yml
name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  set-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: call compostire
        id: composite
        uses: ./.github/workflows/falcon
      - name: display
        run: |
            ls -lrth
