# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/main.yaml
    with:
      keys: "user"
  use-outputs:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Use the outputs
        run: |
          echo "User: ${{ env.user }}"
