name: Hardcoded Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.pr-number }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          # Hardcode the PR number
          PR_NUMBER=143

          # Mask the PR_NUMBER in logs
          echo "::add-mask::$PR_NUMBER"

          # Output the PR_NUMBER to be used by other jobs
          echo "pr-number=$PR_NUMBER" >> $GITHUB_ENV

  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    steps:
      - name: Display PR number
        env:
          PR_NUMBER: ${{ env.pr-number }}
        run: |
           # This will display the masked PR number
           echo "PR: $PR_NUMBER"
