# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/main.yaml
    with:
      keys: "user"

    steps:
      - name: Use the outputs
        run: |
          echo "User: ${{ steps.read-config.outputs.user }}"
          echo "DB Token: ${{ steps.read-config.outputs.db_token }}"
          echo "API Token: ${{ steps.read-config.outputs.api_token }}"
