# .github/workflows/main-workflow.yml
name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  set-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: call compostire
        id: composite
        uses: ./.github/workflows/falcon
      
      - name: display
        shell: bash
        run: |
            ls -lrth
      - name: Display CI Token
        shell: bash
        run: |
            CITOKEN=$(yq eval '.CI_TOKEN' config.yaml)

      # - name: Fetch latest version of Falcon image
      #   id: falcon
      #   run: |
      #       # Fetch CITOKEN from environment
      #       CITOKEN=${{ env.CI_TOKEN }}

      #       # Use CITOKEN in a command without printing it
      #       falcon_image_path=$(bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh) -t falcon-container -u $CITOKEN -s $CITOKEN --get-image-path)

      
