name: Hardcoded Credentials Workflow

on:
  push:
    branches:
      - main
jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          echo "PR_NUMBER=143" >> $GITHUB_OUTPUT

  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.check-pr.outputs.pr-number }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
           echo "PR: $PR_NUMBER"
