name: Use Dynamic Data Workflow

on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip files from another repo
        run: echo "Hello DevOps" >> $RUNNER_TEMP/myfile.txt

  list_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: list file
        run: ls -la $RUNNER_TEMP/myfile.txt
     
      - name: cat  file
        run: cat $RUNNER_TEMP/myfile.txt
