name: Use Dynamic Data Workflow

on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: List runner data
        run: ls -la $RUNNER_TEMP/

      - name: create file
        run: echo "Hello DevOps" >> my_file.txt && mv my_file.txt $RUNNER_TEMP/

  list_file:
    runs-on: ubuntu-latest
    needs: create_file
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: list file
        run: ls -la $RUNNER_TEMP/
     
      # - name: cat  file
      #   run: cat $RUNNER_TEMP/myfile.txt
