name: Test Migrations
on:
  push:
    branches:
      - main

jobs:
  Docker_build:
    name: Code checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Create Custom Network
        run: docker network create my-network
      - name: Run Migrations
        run: |
          docker run --name percona --network my-network -e MYSQL_ROOT_PASSWORD=ci -p 3306:3306 -d percona:5.6
          docker run --network my-network mysql /bin/sh -c "sleep 60 && mysql -hpercona -uroot -pci --execute='SET FOREIGN_KEY_CHECKS=0'"
