name: Use Dynamic Data Workflow

on:
  push:
    branches:
      - main

jobs:
  run_mvn:
    runs-on: ubuntu-latest
    steps:
    - name: Call Reusable Workflow
      uses: ./.github/workflows/mvn-cmd.yml
      with:
        inputs: 'app2_cluster_name:.app2.cluster-name,app2_app_name:.app2.app-name' 

  # print-data:
  #   needs: dynamic-data
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print outputs
  #       run: |
  #         IFS=';' read -r -a outputs <<< "${{ needs.dynamic-data.outputs.outputs }}"
  #         for output in "${outputs[@]}"; do
  #           IFS=',' read -r name value <<< "$output"
  #           echo "$name: $value"
  #         done
