name: Example Workflow

on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run YAML to Github Output Action
      id: yaml-output
      uses: christian-ci/action-yaml-github-output@v2
      with:
        file_path: config.yaml
        main_key: regions
        sub_key: us-west-1

  print_job:
    runs-on: ubuntu-latest
    needs: example_job
    steps:
    - name: Print Variables
      run: |
        echo "Cluster Name from Outputs: ${{ needs.example_job.outputs.cluster_name }}"
        echo "App Name from Outputs: ${{ needs.example_job.outputs.app_name }}"

  # print_job:
  #   runs-on: ubuntu-latest
  #   needs: example_job
  #   steps:
  #   - name: Print Variables
  #     run: |
  #       echo "Cluster Name from Outputs: ${{ needs.example_job.outputs.cluster_name }}"
  #       echo "App Name from Outputs: ${{ needs.example_job.outputs.app_name }}"

  # run_mvn:
  #   runs-on: ubuntu-latest
  #   needs: read_config_file
  #   steps:
  #   - name: Call Reusable Workflow
  #     uses: ./.github/workflows/mvn-cmd.yml
  #     with:
  #       cluster_name: ${{ needs.read_config_file.outputs.cluster_name }}
  #       app_name: ${{ needs.read_config_file.outputs.app_name }}
