name: Example Workflow

on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      cluster_name: ${{ steps.yaml-output.outputs.cluster-name }}
      app_name: ${{ steps.yaml-output.outputs.app-name }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run YAML to Github Output Action
      id: yaml-output
      uses: christian-ci/action-yaml-github-output@v2
      with:
        file_path: path/to/settings.yaml
        main_key: regions
        sub_key: us-west-1

  print_job:
    runs-on: ubuntu-latest
    needs: example_job
    steps:
    - name: Print Variables
      run: |
        echo "Cluster Name from Outputs: ${{ needs.example_job.outputs.cluster_name }}"
        echo "App Name from Outputs: ${{ needs.example_job.outputs.app_name }}"
