name: Use Dynamic Data Workflow

on:
  push:
    branches:
      - main
jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: ls -la $RUNNER_TEMP/
      - name: Create
        run: echo "Hello DevOps" >> $RUNNER_TEMP/myfile.txt
      - name: List
        run: ls -la $RUNNER_TEMP/

  list_file:
    runs-on: ubuntu-latest
    needs: create_file
    steps:  
      - name: List
        run: ls -la $RUNNER_TEMP/
