name: Config Workflow

on:
  push:
    branches:
      - main

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read YAML File
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_yaml
        with:
          config: ${{ github.workspace }}/examples/config.yaml

      - name: Use YAML Values
        run: |
          echo DB User: ${{ steps.read_yaml.outputs['db_user'] }}
          echo DB Pass: ${{ steps.read_yaml.outputs['db_pass'] }}
          echo DB Host: ${{ steps.read_yaml.outputs['db_host'] }}
          echo DB Port: ${{ steps.read_yaml.outputs['db_port'] }}

  
