name: Main Workflow
on:
  push:
    branches:
      - main
jobs:
  fetch-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Set hardcoded user and password
        id: set-creds
        run: |
          # Hardcode the user and password values
          user="abc"
          password="abc@123"

          # Mask the user and password in the logs
          echo "::add-mask::$user"
          echo "::add-mask::$password"

          # Set environment variables for the next job
          echo "USER=$user" >> $GITHUB_ENV
          echo "PASSWORD=$password" >> $GITHUB_ENV

  call-api:
    needs: fetch-credentials
    runs-on: ubuntu-latest
    steps:
      - name: Display user and password
        env:
          USER: ${{ env.USER }}
          PASSWORD: ${{ env.PASSWORD }}
        run: |
          # Display the user and password (masked in logs)
          echo "User: $USER"
          echo "Password: $PASSWORD"
