name: Restart Service

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (dev, prod, e2e, uat)'
        required: true
        type: choice
        options:
          - dev
          - prod
          - e2e
          - uat
      namespace:
        description: 'Enter the namespace'
        required: true
        type: string
      deployment_name:
        description: 'Enter the deployment name'
        required: true
        type: string

jobs:
  restart-service:
    runs-on: ubuntu-latest
    needs: Deploy_Cert
    steps:
      - uses: ./.github/workflows/cnative-restart-dev.yml@develop-bos-digital
        with:
          DEPLOYMENT_NAME: ${{ github.event.inputs.deployment_name }}
          NAMESPACE: ${{ github.event.inputs.namespace }}
          # Use a map to define environment-specific values
          ENVIRONMENT_CONFIG: |
            {
              "dev": {
                "cluster_name": "ge4-bos-cn-dv",
                "cluster_location": "us-east4",
                "gcp_project": "app-bos-cn-dv-5gu9",
                "gcp_project_number": "644y5485895",
                "pool_name": "app-bos-dv-wi-pool-01",
                "provider_name": "app-bos-dv-wi-github-provider"
              },
            }
          # Access environment-specific values using JMESPath expression
          CLUSTER_NAME: ${{ fromJson(steps.parse-inputs.outputs.environment_config).$(github.event.inputs.environment).cluster_name }}
          CLUSTER_LOCATION: ${{ fromJson(steps.parse-inputs.outputs.environment_config).$(github.event.inputs.environment).cluster_location }}
          GCP_PROJECT: ${{ fromJson(steps.parse-inputs.outputs.environment_config).$(github.event.inputs.environment).gcp_project }}
          GCP_PROJECT_NUMBER: ${{ fromJson(steps.parse-inputs.outputs.environment_config).$(github.event.inputs.environment).gcp_project_number }}
          POOL_NAME: ${{ fromJson(steps.parse-inputs.outputs.environment_config).$(github.event.inputs.environment).pool_name }}
          PROVIDER_NAME: ${{ fromJson(steps.parse-inputs.outputs.environment_config).$(github.event.inputs.environment).provider_name }}
