name: Test Migrations
on:
  push:

jobs:
  Docker_build:
    name: Code checkout
    runs-on: ubuntu-latest
    services:
      percona:
        image: percona:5.6
        env:
          MYSQL_ROOT_PASSWORD: ci
        ports: 
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --name percona --hostname percona --network percona
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: run migrations
        run: docker run --network percona --network-alias=percona --entrypoint /bin/sh mysql -c "sleep 60 && mysql -hpercona -uroot -pci --execute="SET FOREIGN_KEY_CHECKS=0""
