# .github/workflows/main-workflow.yml
name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  set-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: call compostire
        id: composite
        uses: ./.github/workflows/falcon
      
      - name: display
        shell: bash
        run: |
            ls -lrth
      - name: Display CI Token
        shell: bash
        run: |
            CITOKEN=$(yq eval '.CI_TOKEN' config.yaml)
            echo $CITOKEN
            falcon_image_path=curl https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/abc.txt -t falcon-container -u "$CITOKEN" -s "$CITOKEN"

      
