# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/main.yaml
    with:
      keys: "user"
    steps:
      - name: Use the outputs
        run: |
          echo "User: ${{ env.user }}"
          echo "DB Token: ${{ env.db_token }}"
          echo "API Token: ${{ env.api_token }}"