name: Reusable Workflow

on:
  workflow_call:
    inputs:
      keys:
        description: "Comma-separated list of keys to retrieve from config.yaml"
        required: true
        type: string

jobs:
  set-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          pip install yq

      - name: Read from config.yaml and set outputs
        id: read-config
        run: |
          keys="${{ inputs.keys }}"
          IFS=',' read -ra key_array <<< "$keys"

          for key in "${key_array[@]}"; do
            # Use yq to extract the value for each key directly
            value=$(yq eval ".${key}" config.yaml)
            
            if [ -n "$value" ]; then
              echo "${key}=${value}" >> $GITHUB_ENV
            else
              echo "Key '$key' not found in config.yaml"
            fi
          done
