name: Example Workflow

on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run YAML to Github Output Action
      id: yaml-output
      uses: christian-ci/action-yaml-github-output@v2
      with:
        file_path: config.yaml
        main_key: regions
        sub_key: us-west-1
        name-transformation: none

    - name: Print Variables
      run: |
        
        echo "Cluster Name caps : ${{ env.CLUSTER_NAME }}"
        echo "App Name small {{ env.APP_NAME }}"
        echo "DB NAME caps : ${{ env.DB_NAME }}"
        echo "Cluster Name small : ${{ env.cluster_name }}"
        echo "App Name small {{ env.app_name }}"
        echo "DB Name small : ${{ env.db_name }}"
