# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      # Define any secrets needed here
    outputs:
      # Define any outputs needed here

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Print Cluster and App Name
        run: |
          echo "Cluster Name: ${{ inputs.cluster_name }}"
          echo "App Name: ${{ inputs.app_name }}"
