name: Dynamic Data Workflow

on:
  workflow_call:
    inputs:
      inputs:
        description: 'List of inputs in the format key:path'
        required: true
        type: string
    outputs:
      outputs:
        description: 'Comma-separated list of output keys and values'
        required: true
        type: string

jobs:
  process-data:
    runs-on: ubuntu-latest
    outputs:
      outputs: ${{ steps.set-outputs.outputs.outputs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # - name: Read YAML and set outputs
      #   id: set-outputs
      #   run: |
      #     # Prepare the GITHUB_OUTPUT file
      #     echo "" > $GITHUB_OUTPUT

      #     # Read inputs and prepare outputs
      #     IFS=',' read -r -a keys <<< "${{ inputs.inputs }}"
      #     OUTPUTS=""

      #     for key in "${keys[@]}"; do
      #       IFS=':' read -r output_name yaml_path <<< "$key"
      #       VALUE=$(yq eval "$yaml_path" config.yaml)
      #       echo "$output_name=$VALUE" >> $GITHUB_OUTPUT
      #       OUTPUTS+="$output_name,$VALUE;"
      #     done

      #     # Set final GitHub Actions outputs
      #     echo "outputs=${OUTPUTS%?}" >> $GITHUB_OUTPUT  # Remove trailing semicolon
