name: Reusable Workflow
runs:
    using: "composite"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: create file
        shell: bash
        run: |
            ls -lrth
            touch a b c